# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parley' do
  pod 'NVActivityIndicatorView'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
use_frameworks!

  # Pods for Parley

end
